drop unused (and failling with python >= 3.13) import of cgi module
Commit 2b44c9c already replaced all usages of this deprecated module,
leaving only the import behind.

With python versions from 3.13 onward, this causes the error

    ModuleNotFoundError: No module named 'cgi'

Dropping the import makes things work again.